name: Publicar en AUR

on:
  release:
    types: [published]

jobs:
  aur-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Descargar código
        uses: actions/checkout@v4

      - name: 🚀 Subir al Arch User Repository
        uses: KSXGitHub/github-actions-deploy-aur@v3.0.1
        with:
          pkgname: asfy-vol
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to release ${{ github.event.release.tag_name }}"
          ssh_keyscan_types: rsa,ecdsa,ed25519
